# ==========================================================================
# CRE PROJECT SETTINGS FILE — LexOracle Risk Guard
# ==========================================================================

staging-settings:
  cre-cli:
    don-family: "zone-a"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

production-settings:
  cre-cli:
    don-family: "zone-a"
  account:
    workflow-owner-address: "0xadB60036FE9d4c269Ed5ca8C5958dd29bc66D814"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://sepolia.base.org
    - chain-name: ethereum-mainnet
      url: https://ethereum-rpc.publicnode.com
